version: '3.8'

services:
  bot:
    build: .
    container_name: assistant-ia
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - local.env
    volumes:
      - ./credentials.json:/app/credentials.json 