version: '3.8'

services:
  bot:
    build: .
    container_name: assistant-ia
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - local.env
    volumes:
      - ./credentials.json:/app/credentials.json
      - audio_data:/app/audio_data
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@postgres:5432/assistant_ia
      - REDIS_URL=redis://redis:6379/0

  postgres:
    image: postgres:15
    container_name: assistant-ia-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: postgres
      POSTGRES_DB: assistant_ia
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: assistant-ia-redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  audio_data: 